import { Exercise } from '@/store/types';

export const baseExercises: Record<string, Exercise> = {
  // ═══════════════════════════════════════════════════════
  // PUSH CHAIN — Floor
  // ═══════════════════════════════════════════════════════
  knee_pushup: {
    id: 'knee_pushup',
    name: 'Knee Push-Up',
    group: 'Push',
    equipment: ['None'],
    level: 1,
    targetRepsToUnlock: 15,
    targetSetsToUnlock: 3,
    nextProgressionId: 'pushup',
    prevProgressionId: null,
    formCues: [
      'Hands shoulder-width apart',
      'Straight line from knees to shoulders',
      'Touch chest to floor',
      'Full lockout at top',
    ],
  },
  pushup: {
    id: 'pushup',
    name: 'Push-Up',
    group: 'Push',
    equipment: ['None'],
    level: 2,
    targetRepsToUnlock: 12,
    targetSetsToUnlock: 3,
    nextProgressionId: 'diamond_pushup',
    prevProgressionId: 'knee_pushup',
    formCues: [
      'Hands shoulder-width apart',
      'Hollow body position throughout',
      'Elbows at 45°, not flared',
      'Full ROM — chest to floor',
    ],
  },
  diamond_pushup: {
    id: 'diamond_pushup',
    name: 'Diamond Push-Up',
    group: 'Push',
    equipment: ['None'],
    level: 4,
    targetRepsToUnlock: 10,
    targetSetsToUnlock: 3,
    nextProgressionId: 'archer_pushup',
    prevProgressionId: 'pushup',
    formCues: [
      'Hands together forming a diamond',
      'Keep elbows close to body',
      'Protract scapulae at the top',
      'Slow eccentric — 3 seconds down',
    ],
  },
  archer_pushup: {
    id: 'archer_pushup',
    name: 'Archer Push-Up',
    group: 'Push',
    equipment: ['None'],
    level: 6,
    targetRepsToUnlock: 8,
    targetSetsToUnlock: 3,
    nextProgressionId: 'pseudo_planche_pushup',
    prevProgressionId: 'diamond_pushup',
    formCues: [
      'Wide hand placement',
      'Shift weight fully to working arm',
      'Straight assist arm — no bend',
      'Touch chest to working hand',
    ],
  },
  pseudo_planche_pushup: {
    id: 'pseudo_planche_pushup',
    name: 'Pseudo Planche Push-Up',
    group: 'Push',
    equipment: ['None'],
    level: 8,
    targetRepsToUnlock: 8,
    targetSetsToUnlock: 3,
    nextProgressionId: 'tuck_planche_pushup',
    prevProgressionId: 'archer_pushup',
    formCues: [
      'Hands by waist, fingers pointing back',
      'Lean forward aggressively',
      'Protract scapulae hard',
      'Keep hips level with shoulders',
    ],
  },
  tuck_planche_pushup: {
    id: 'tuck_planche_pushup',
    name: 'Tuck Planche Push-Up',
    group: 'Push',
    equipment: ['Parallettes'],
    level: 10,
    targetRepsToUnlock: 5,
    targetSetsToUnlock: 3,
    nextProgressionId: null,
    prevProgressionId: 'pseudo_planche_pushup',
    formCues: [
      'Lean forward until hips float',
      'Tuck knees tight to chest',
      'Protract and depress scapulae',
      'Push through full ROM',
    ],
  },

  // ═══════════════════════════════════════════════════════
  // PUSH CHAIN — Rings/Parallettes
  // ═══════════════════════════════════════════════════════
  ring_pushup: {
    id: 'ring_pushup',
    name: 'Ring Push-Up',
    group: 'Push',
    equipment: ['Rings'],
    level: 3,
    targetRepsToUnlock: 12,
    targetSetsToUnlock: 3,
    nextProgressionId: 'ring_dip',
    prevProgressionId: null,
    formCues: [
      'Rings at chest height',
      'Turn rings out (RTO) at top',
      'Control the wobble — squeeze tight',
      'Full lockout with rings turned out',
    ],
  },
  ring_dip: {
    id: 'ring_dip',
    name: 'Ring Dip',
    group: 'Push',
    equipment: ['Rings'],
    level: 5,
    targetRepsToUnlock: 8,
    targetSetsToUnlock: 3,
    nextProgressionId: 'advanced_ring_dip',
    prevProgressionId: 'ring_pushup',
    formCues: [
      'Start locked out at top',
      'Dip below 90° elbow angle',
      'Keep rings close to body',
      'Turn rings out at top of each rep',
    ],
  },
  advanced_ring_dip: {
    id: 'advanced_ring_dip',
    name: 'RTO Dip',
    group: 'Push',
    equipment: ['Rings'],
    level: 8,
    targetRepsToUnlock: 5,
    targetSetsToUnlock: 3,
    nextProgressionId: 'ring_muscle_up',
    prevProgressionId: 'ring_dip',
    formCues: [
      'Rings turned out throughout the entire rep',
      'Deep dip — shoulders below elbows',
      'Maintain RTO in the bottom',
      'Slow and controlled — no kipping',
    ],
  },
  ring_muscle_up: {
    id: 'ring_muscle_up',
    name: 'Ring Muscle-Up',
    group: 'Push',
    equipment: ['Rings'],
    level: 11,
    targetRepsToUnlock: 3,
    targetSetsToUnlock: 3,
    nextProgressionId: null,
    prevProgressionId: 'advanced_ring_dip',
    formCues: [
      'False grip is essential',
      'Pull high — rings to chest',
      'Fast transition — lean forward aggressively',
      'Press out to full lockout',
    ],
  },

  // ═══════════════════════════════════════════════════════
  // PUSH CHAIN — Handstand
  // ═══════════════════════════════════════════════════════
  wall_pike_pushup: {
    id: 'wall_pike_pushup',
    name: 'Wall Pike Push-Up',
    group: 'Push',
    equipment: ['Wall'],
    level: 3,
    targetRepsToUnlock: 10,
    targetSetsToUnlock: 3,
    nextProgressionId: 'elevated_pike_pushup',
    prevProgressionId: null,
    formCues: [
      'Feet on wall, hands on floor',
      'Pike position — hips high',
      'Head touches floor between hands',
      'Push straight up — vertical pressing',
    ],
  },
  elevated_pike_pushup: {
    id: 'elevated_pike_pushup',
    name: 'Elevated Pike Push-Up',
    group: 'Push',
    equipment: ['Wall'],
    level: 5,
    targetRepsToUnlock: 8,
    targetSetsToUnlock: 3,
    nextProgressionId: 'wall_hspu',
    prevProgressionId: 'wall_pike_pushup',
    formCues: [
      'Feet elevated on box or chair',
      'More vertical torso than basic pike',
      'Touch head to floor',
      'Drive through shoulders at top',
    ],
  },
  wall_hspu: {
    id: 'wall_hspu',
    name: 'Wall HSPU',
    group: 'Push',
    equipment: ['Wall'],
    level: 8,
    targetRepsToUnlock: 5,
    targetSetsToUnlock: 3,
    nextProgressionId: 'freestanding_hspu',
    prevProgressionId: 'elevated_pike_pushup',
    formCues: [
      'Chest to wall — hands close to wall',
      'Full ROM — head to floor',
      'Stack shoulders over wrists',
      'Control the descent — no crashing',
    ],
  },
  freestanding_hspu: {
    id: 'freestanding_hspu',
    name: 'Freestanding HSPU',
    group: 'Push',
    equipment: ['None'],
    level: 12,
    targetRepsToUnlock: 3,
    targetSetsToUnlock: 3,
    nextProgressionId: null,
    prevProgressionId: 'wall_hspu',
    formCues: [
      'Kick up to freestanding handstand',
      'Maintain balance through fingertips',
      'Slow descent — head to floor',
      'Press back up without losing balance',
    ],
  },

  // ═══════════════════════════════════════════════════════
  // PULL CHAIN — Bar
  // ═══════════════════════════════════════════════════════
  dead_hang: {
    id: 'dead_hang',
    name: 'Dead Hang',
    group: 'Pull',
    equipment: ['Pullup Bar'],
    level: 1,
    targetRepsToUnlock: 30, // 30-second hold counted as 1 "rep"
    targetSetsToUnlock: 3,
    nextProgressionId: 'scapula_pull',
    prevProgressionId: null,
    formCues: [
      'Overhand grip, shoulder width',
      'Shoulders packed — no shrugging',
      'Straight arms, relaxed lats',
      'Count seconds as reps',
    ],
  },
  scapula_pull: {
    id: 'scapula_pull',
    name: 'Scapula Pull',
    group: 'Pull',
    equipment: ['Pullup Bar'],
    level: 2,
    targetRepsToUnlock: 12,
    targetSetsToUnlock: 3,
    nextProgressionId: 'negative_pullup',
    prevProgressionId: 'dead_hang',
    formCues: [
      'Arms stay straight',
      'Retract and depress scapulae only',
      'Chest lifts toward bar',
      'Focus on shoulder blade movement',
    ],
  },
  negative_pullup: {
    id: 'negative_pullup',
    name: 'Negative Pull-Up',
    group: 'Pull',
    equipment: ['Pullup Bar'],
    level: 3,
    targetRepsToUnlock: 8,
    targetSetsToUnlock: 3,
    nextProgressionId: 'pullup',
    prevProgressionId: 'scapula_pull',
    formCues: [
      'Jump or step up to chin-over-bar',
      'Lower for 5+ seconds',
      'Control the entire descent',
      'Dead hang at the bottom',
    ],
  },
  pullup: {
    id: 'pullup',
    name: 'Pull-Up',
    group: 'Pull',
    equipment: ['Pullup Bar'],
    level: 4,
    targetRepsToUnlock: 10,
    targetSetsToUnlock: 3,
    nextProgressionId: 'archer_pullup',
    prevProgressionId: 'negative_pullup',
    formCues: [
      'Overhand grip, shoulder width',
      'Chin over bar at top',
      'Dead hang at bottom — full ROM',
      'No kipping — strict form',
    ],
  },
  archer_pullup: {
    id: 'archer_pullup',
    name: 'Archer Pull-Up',
    group: 'Pull',
    equipment: ['Pullup Bar'],
    level: 7,
    targetRepsToUnlock: 6,
    targetSetsToUnlock: 3,
    nextProgressionId: 'chest_to_bar_pullup',
    prevProgressionId: 'pullup',
    formCues: [
      'Wide grip — one arm pulls, one assists',
      'Assist arm stays straight',
      'Pull to working arm side',
      'Full ROM each rep',
    ],
  },
  chest_to_bar_pullup: {
    id: 'chest_to_bar_pullup',
    name: 'Chest-to-Bar Pull-Up',
    group: 'Pull',
    equipment: ['Pullup Bar'],
    level: 9,
    targetRepsToUnlock: 5,
    targetSetsToUnlock: 3,
    nextProgressionId: 'bar_muscle_up',
    prevProgressionId: 'archer_pullup',
    formCues: [
      'Pull until chest touches bar',
      'Lean back slightly at top',
      'Aggressive lat engagement',
      'Controlled negative',
    ],
  },
  bar_muscle_up: {
    id: 'bar_muscle_up',
    name: 'Bar Muscle-Up',
    group: 'Pull',
    equipment: ['Pullup Bar'],
    level: 11,
    targetRepsToUnlock: 3,
    targetSetsToUnlock: 3,
    nextProgressionId: null,
    prevProgressionId: 'chest_to_bar_pullup',
    formCues: [
      'Explosive pull — generate height',
      'Lean forward over the bar at transition',
      'Press out to full lockout on top',
      'Controlled descent back to hang',
    ],
  },

  // ═══════════════════════════════════════════════════════
  // PULL CHAIN — Rings
  // ═══════════════════════════════════════════════════════
  ring_row: {
    id: 'ring_row',
    name: 'Ring Row',
    group: 'Pull',
    equipment: ['Rings'],
    level: 2,
    targetRepsToUnlock: 12,
    targetSetsToUnlock: 3,
    nextProgressionId: 'ring_pullup',
    prevProgressionId: null,
    formCues: [
      'Body straight — plank position',
      'Pull rings to chest',
      'Squeeze shoulder blades together',
      'The more horizontal, the harder',
    ],
  },
  ring_pullup: {
    id: 'ring_pullup',
    name: 'Ring Pull-Up',
    group: 'Pull',
    equipment: ['Rings'],
    level: 5,
    targetRepsToUnlock: 8,
    targetSetsToUnlock: 3,
    nextProgressionId: 'ring_muscle_up_pull',
    prevProgressionId: 'ring_row',
    formCues: [
      'False grip recommended',
      'Pull rings to armpits',
      'Supinate at the top if possible',
      'Full dead hang at bottom',
    ],
  },
  ring_muscle_up_pull: {
    id: 'ring_muscle_up_pull',
    name: 'Ring Muscle-Up',
    group: 'Pull',
    equipment: ['Rings'],
    level: 11,
    targetRepsToUnlock: 3,
    targetSetsToUnlock: 3,
    nextProgressionId: null,
    prevProgressionId: 'ring_pullup',
    formCues: [
      'False grip is mandatory',
      'Pull high — rings below chest',
      'Aggressive lean-forward transition',
      'Full lockout at top in support hold',
    ],
  },

  // ═══════════════════════════════════════════════════════
  // CORE CHAIN
  // ═══════════════════════════════════════════════════════
  dead_bug: {
    id: 'dead_bug',
    name: 'Dead Bug',
    group: 'Core',
    equipment: ['None'],
    level: 1,
    targetRepsToUnlock: 15,
    targetSetsToUnlock: 3,
    nextProgressionId: 'hollow_body',
    prevProgressionId: null,
    formCues: [
      'Lower back pressed into floor',
      'Opposite arm and leg extend',
      'Breathe out as you extend',
      'Slow and controlled — no rushing',
    ],
  },
  hollow_body: {
    id: 'hollow_body',
    name: 'Hollow Body Hold',
    group: 'Core',
    equipment: ['None'],
    level: 3,
    targetRepsToUnlock: 30, // seconds as reps
    targetSetsToUnlock: 3,
    nextProgressionId: 'l_sit_tuck',
    prevProgressionId: 'dead_bug',
    formCues: [
      'Lower back glued to floor',
      'Arms overhead, legs straight',
      'Point toes — squeeze everything',
      'Count seconds as reps',
    ],
  },
  l_sit_tuck: {
    id: 'l_sit_tuck',
    name: 'Tuck L-Sit',
    group: 'Core',
    equipment: ['Parallettes'],
    level: 5,
    targetRepsToUnlock: 15, // seconds
    targetSetsToUnlock: 3,
    nextProgressionId: 'l_sit',
    prevProgressionId: 'hollow_body',
    formCues: [
      'Hands on parallettes, depress shoulders',
      'Tuck knees to chest',
      'Lift hips off the ground',
      'Count seconds as reps',
    ],
  },
  l_sit: {
    id: 'l_sit',
    name: 'L-Sit',
    group: 'Core',
    equipment: ['Parallettes'],
    level: 7,
    targetRepsToUnlock: 10, // seconds
    targetSetsToUnlock: 3,
    nextProgressionId: 'v_sit',
    prevProgressionId: 'l_sit_tuck',
    formCues: [
      'Legs straight and parallel to floor',
      'Depress shoulders hard',
      'Point toes forward',
      'Count seconds as reps',
    ],
  },
  v_sit: {
    id: 'v_sit',
    name: 'V-Sit',
    group: 'Core',
    equipment: ['Parallettes'],
    level: 10,
    targetRepsToUnlock: 5, // seconds
    targetSetsToUnlock: 3,
    nextProgressionId: null,
    prevProgressionId: 'l_sit',
    formCues: [
      'Legs above horizontal — compress hard',
      'Lean back slightly for balance',
      'Straight legs, pointed toes',
      'Count seconds as reps',
    ],
  },

  // ═══════════════════════════════════════════════════════
  // LEGS CHAIN
  // ═══════════════════════════════════════════════════════
  squat: {
    id: 'squat',
    name: 'Bodyweight Squat',
    group: 'Legs',
    equipment: ['None'],
    level: 1,
    targetRepsToUnlock: 20,
    targetSetsToUnlock: 3,
    nextProgressionId: 'bulgarian_split_squat',
    prevProgressionId: null,
    formCues: [
      'Feet shoulder-width apart',
      'Break at hips and knees together',
      'Knees track over toes',
      'Full depth — hip crease below knee',
    ],
  },
  bulgarian_split_squat: {
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    group: 'Legs',
    equipment: ['None'],
    level: 4,
    targetRepsToUnlock: 10,
    targetSetsToUnlock: 3,
    nextProgressionId: 'pistol_squat_assist',
    prevProgressionId: 'squat',
    formCues: [
      'Rear foot elevated on bench/chair',
      'Front knee tracks over toes',
      'Upright torso',
      'Full depth on each rep',
    ],
  },
  pistol_squat_assist: {
    id: 'pistol_squat_assist',
    name: 'Assisted Pistol Squat',
    group: 'Legs',
    equipment: ['None'],
    level: 7,
    targetRepsToUnlock: 8,
    targetSetsToUnlock: 3,
    nextProgressionId: 'pistol_squat',
    prevProgressionId: 'bulgarian_split_squat',
    formCues: [
      'Hold a pole or doorframe for balance',
      'Single leg — other leg extended forward',
      'Full depth — hamstring to calf',
      'Use minimal assistance',
    ],
  },
  pistol_squat: {
    id: 'pistol_squat',
    name: 'Pistol Squat',
    group: 'Legs',
    equipment: ['None'],
    level: 9,
    targetRepsToUnlock: 5,
    targetSetsToUnlock: 3,
    nextProgressionId: null,
    prevProgressionId: 'pistol_squat_assist',
    formCues: [
      'Stand on one leg',
      'Extend other leg forward, straight',
      'Full depth — no assistance',
      'Stand up without losing balance',
    ],
  },
  nordic_curl: {
    id: 'nordic_curl',
    name: 'Nordic Curl',
    group: 'Legs',
    equipment: ['None'],
    level: 7,
    targetRepsToUnlock: 5,
    targetSetsToUnlock: 3,
    nextProgressionId: null,
    prevProgressionId: null,
    formCues: [
      'Kneel on soft surface, ankles anchored',
      'Lower torso slowly using hamstrings',
      'Keep hips slightly flexed or straight',
      'Push back up with minimal hand help',
    ],
  },
  jump_squat: {
    id: 'jump_squat',
    name: 'Jump Squat',
    group: 'Legs',
    equipment: ['None'],
    level: 3,
    targetRepsToUnlock: 12,
    targetSetsToUnlock: 3,
    nextProgressionId: null,
    prevProgressionId: 'squat',
    formCues: [
      'Squat down to parallel',
      'Explode upwards aggressively',
      'Land softly on balls of feet',
      'Reset and repeat immediately',
    ],
  },
  single_leg_glute_bridge: {
    id: 'single_leg_glute_bridge',
    name: 'Single Leg Glute Bridge',
    group: 'Legs',
    equipment: ['None'],
    level: 2,
    targetRepsToUnlock: 15,
    targetSetsToUnlock: 3,
    nextProgressionId: 'nordic_curl',
    prevProgressionId: null,
    formCues: [
      'Lie on back, one leg bent, one extended',
      'Drive through heel of bent leg',
      'Squeeze glute at the top',
      'Lower with control',
    ],
  },
  // ═══════════════════════════════════════════════════════
  // WARMUP & COOLDOWN
  // ═══════════════════════════════════════════════════════
  wrist_stretches: {
    id: 'wrist_stretches',
    name: 'Wrist Prep',
    group: 'Push',
    equipment: ['None'],
    level: 0,
    targetRepsToUnlock: 1,
    targetSetsToUnlock: 1,
    formCues: ['Palms down, lean forward', 'Palms up, fingers back', 'Wrist circles 30s'],
  },
  band_dislocates: {
    id: 'band_dislocates',
    name: 'Shoulder Mobility',
    group: 'Push',
    equipment: ['None'],
    level: 0,
    targetRepsToUnlock: 1,
    targetSetsToUnlock: 1,
    formCues: ['Straight arms throughout', 'Pull band/towel apart', 'Slow and controlled'],
  },
  scapular_pushups: {
    id: 'scapular_pushups',
    name: 'Scapular Awakening',
    group: 'Push',
    equipment: ['None'],
    level: 0,
    targetRepsToUnlock: 1,
    targetSetsToUnlock: 1,
    formCues: ['Arms stay locked straight', 'Pinch shoulder blades slowly', 'Push away as high as possible'],
  },
  deep_squat_sit: {
    id: 'deep_squat_sit',
    name: 'Deep Squat Sit',
    group: 'Legs',
    equipment: ['None'],
    level: 0,
    targetRepsToUnlock: 1,
    targetSetsToUnlock: 1,
    formCues: ['Heels flat on floor', 'Pry knees open with elbows', 'Straight back'],
  },
  passive_dead_hang: {
    id: 'passive_dead_hang',
    name: 'Spinal Decompression',
    group: 'Pull',
    equipment: ['Pullup Bar'],
    level: 0,
    targetRepsToUnlock: 1,
    targetSetsToUnlock: 1,
    formCues: ['Relax completely', 'Let lats stretch', 'Breathe deep'],
  },
  doorway_pec_stretch: {
    id: 'doorway_pec_stretch',
    name: 'Chest Opener',
    group: 'Push',
    equipment: ['Wall'],
    level: 0,
    targetRepsToUnlock: 1,
    targetSetsToUnlock: 1,
    formCues: ['Fix forearm on frame', 'Gently lean forward/turn', 'Switch sides'],
  },
  seated_pike_stretch: {
    id: 'seated_pike_stretch',
    name: 'Posterior Chain',
    group: 'Legs',
    equipment: ['None'],
    level: 0,
    targetRepsToUnlock: 1,
    targetSetsToUnlock: 1,
    formCues: ['Legs straight out', 'Reach for toes', 'Exhale into the stretch'],
  },
  // ═══════════════════════════════════════════════════════
  // VR-THEMED WARMUP & COOLDOWN
  // ═══════════════════════════════════════════════════════
  neck_rolls: {
    id: 'neck_rolls',
    name: 'Headset Prep',
    group: 'Core',
    equipment: ['None'],
    level: 0,
    targetRepsToUnlock: 1,
    targetSetsToUnlock: 1,
    formCues: ['Slowly look L/R/U/D', 'Half-moons only — no circles', 'Relax shoulders down'],
  },
  helicopter_arms: {
    id: 'helicopter_arms',
    name: 'Helicopter Arms',
    group: 'Push',
    equipment: ['None'],
    level: 0,
    targetRepsToUnlock: 1,
    targetSetsToUnlock: 1,
    formCues: ['Huge arm circles', '30s forward, 30s back', 'Keep core tight'],
  },
  wrist_figure_eights: {
    id: 'wrist_figure_eights',
    name: 'Wrist figure-eights',
    group: 'Push',
    equipment: ['None'],
    level: 0,
    targetRepsToUnlock: 1,
    targetSetsToUnlock: 1,
    formCues: ['Clasp hands together', 'Roll in dynamic figure-eight', 'Fluid movement'],
  },
  matrix_duck: {
    id: 'matrix_duck',
    name: 'The Matrix Duck',
    group: 'Legs',
    equipment: ['None'],
    level: 0,
    targetRepsToUnlock: 1,
    targetSetsToUnlock: 1,
    formCues: ['Drop hips fast', 'Prime knees for agility', 'Keep chest upright'],
  },
  horizon_stare: {
    id: 'horizon_stare',
    name: 'The Horizon Stare',
    group: 'Core',
    equipment: ['None'],
    level: 0,
    targetRepsToUnlock: 1,
    targetSetsToUnlock: 1,
    formCues: ['Take off headset', 'Stare as far as possible', 'Rest eye muscles'],
  },
  chin_tucks: {
    id: 'chin_tucks',
    name: 'Chin Tucks',
    group: 'Core',
    equipment: ['Wall'],
    level: 0,
    targetRepsToUnlock: 1,
    targetSetsToUnlock: 1,
    formCues: ['Stand against wall', 'Tuck chin straight back', 'Massive double chin'],
  },
  forearm_massage: {
    id: 'forearm_massage',
    name: 'Forearm Massage',
    group: 'Push',
    equipment: ['None'],
    level: 0,
    targetRepsToUnlock: 1,
    targetSetsToUnlock: 1,
    formCues: ['Use opposite thumb', 'Rub out tight forearms', 'Squeeze and release'],
  },
};

// Initial unlocked exercises — root of each progression chain
export const initialUnlockedExercises: string[] = [
  'knee_pushup',      // Push floor chain
  'ring_pushup',      // Push rings chain
  'wall_pike_pushup', // Push handstand chain
  'dead_hang',        // Pull bar chain
  'ring_row',         // Pull rings chain
  'dead_bug',         // Core chain
  'squat',            // Legs chain
  'nordic_curl',      // Direct leg skill
  'jump_squat',       // Power
  'single_leg_glute_bridge', // Posterior
  'wrist_stretches',
  'band_dislocates',
  'scapular_pushups',
  'deep_squat_sit',
  'passive_dead_hang',
  'doorway_pec_stretch',
  'seated_pike_stretch',
  'neck_rolls',
  'helicopter_arms',
  'wrist_figure_eights',
  'matrix_duck',
  'horizon_stare',
  'chin_tucks',
  'forearm_massage',
];
